CREATE PROCEDURE PROTRY(X NUMBER)
  AS
  BEGIN
  IF MOD(X,2)=0 THEN
  DBMS_OUTPUT.PUT_LINE(X || ' IS EVEN NUMBER');
  ELSE
  DBMS_OUTPUT.PUT_LINE(X || ' IS ODD NUMBER');
    END IF;
  END;
   /